# Generated by Django 3.2 on 2021-04-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='null', upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='tittle',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='description',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
