# Generated by Django 3.2 on 2021-06-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(max_length=255, verbose_name='Contenido'),
        ),
    ]
